# Generated by Django 5.0.3 on 2024-03-21 16:03

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, unique=True)),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airlines',
                'db_table': 'airline',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='Female', max_length=10, verbose_name='Gender')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationality')),
                ('passport_no', models.CharField(max_length=25, verbose_name='Passport No')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='Email')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='Region')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('contact_name', models.CharField(max_length=75, verbose_name='Contact name')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('contact_email', models.CharField(blank=True, max_length=250, verbose_name='Contact Email')),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'db_table': 'clinic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=30, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=70, verbose_name='Name')),
                ('expertise', models.CharField(max_length=75, verbose_name='Expertise')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('contact_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Contact Name')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone')),
                ('contact_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact Email')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('contact_name', models.CharField(max_length=75, verbose_name='Contact Name')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('contact_email', models.CharField(blank=True, max_length=250, verbose_name='Contact Email')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('related_table', models.CharField(blank=True, default='misc', max_length=50, verbose_name='Related Table')),
                ('related_id', models.IntegerField(blank=True, default=0, verbose_name='Related Id')),
                ('file_url', models.FileField(blank=True, null=True, upload_to=main.models.upload_to)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
                'db_table': 'media',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'db_table': 'process',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Debt')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Credit')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client Current',
                'verbose_name_plural': 'Client Currents',
                'db_table': 'client_current',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Request Date')),
                ('process_date', models.DateField(blank=True, null=True, verbose_name='Process Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Planned', 'Planned'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Open', max_length=10, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Client')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.process', verbose_name='Process')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('Arrival', 'Arrival'), ('Departure', 'Departure')], max_length=10, verbose_name='Direction')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('flight_no', models.CharField(max_length=25, verbose_name='Flight No')),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.airline', verbose_name='Airline')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request', verbose_name='Request')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'db_table': 'flight',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='Female', max_length=10, verbose_name='Gender')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='Nationality')),
                ('passport_no', models.CharField(blank=True, max_length=25, verbose_name='Passport No')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request', verbose_name='Request')),
            ],
            options={
                'verbose_name': 'Companion',
                'verbose_name_plural': 'Companions',
                'db_table': 'companion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(null=True, verbose_name='Checkin Date')),
                ('checkout_date', models.DateField(null=True, verbose_name='Checkout Date')),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple'), ('Apart', 'Apart'), ('Suit', 'Suit')], max_length=25, verbose_name='Room Type')),
                ('accomodation_type', models.CharField(choices=[('Half Board', 'Half Board'), ('Full Board', 'Full Board'), ('All Inclusive', 'All Inclusive')], max_length=50, verbose_name='Accomodation Type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hotel', verbose_name='Hotel')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request', verbose_name='Request')),
            ],
            options={
                'verbose_name': 'Accomodation',
                'verbose_name_plural': 'Accomodations',
                'db_table': 'accomodation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Transaction Time')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Price')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Open', max_length=50, verbose_name='Status')),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.clinic', verbose_name='Clinic')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.doctor', verbose_name='Doctor')),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hospital', verbose_name='Hospital')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request', verbose_name='Request')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(default=django.utils.timezone.now, verbose_name='Pickup Date')),
                ('pickup_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Pickup Time')),
                ('pickup_address', models.TextField(default='-', verbose_name='Pickup Address')),
                ('pickup_lat', models.CharField(blank=True, max_length=10, verbose_name='Pickup Lattitude')),
                ('pickup_lon', models.CharField(blank=True, max_length=10, verbose_name='Pickup Longtitude')),
                ('car_plate', models.CharField(blank=True, max_length=20, verbose_name='Car Plate')),
                ('car_type', models.CharField(blank=True, choices=[('Car', 'Car'), ('Minibus', 'Minibus'), ('Bus', 'Bus')], max_length=20, verbose_name='Car Type')),
                ('driver_name', models.CharField(blank=True, max_length=75, verbose_name='Driver Name')),
                ('driver_phone', models.CharField(blank=True, max_length=20, verbose_name='Driver Phone')),
                ('rented_company', models.CharField(blank=True, max_length=75, verbose_name='Rented Company')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Reserved', 'Reserved'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Open', max_length=10, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'db_table': 'transfer',
                'managed': True,
            },
        ),
    ]
